title: "Safwan Safat"
description: "Software Engineer"
github_username: "sfwnsft"

contact:
  email: "safwansafatswe@gmail.com"
  linkedin: "https://www.linkedin.com/in/sfwnsft"
  github: "https://github.com/sfwnsft"

theme: jekyll-theme-minimal
